import '../../domain/entities/allergy.dart';
import '../../domain/entities/nutrition/food_definition.dart';
import '../../domain/entities/nutrition/macros.dart';
import '../../domain/entities/profile/cuisine.dart';

/// On-device food table. Ported from `src/features/nutrition/food-database.ts`.
///
/// Deliberately curated rather than comprehensive. A 900,000-row nutrition
/// database is a search problem; what this product needs is a few hundred foods
/// people in its target markets actually eat, with macros good enough to make a
/// daily total meaningful. The primary market is the US, so American home,
/// diner and fast-food staples are the largest section and the default
/// everywhere the app has to guess (demo seed, slot suggestions, dining
/// fixtures). Mexican-American, Indian, Mediterranean, Middle Eastern and East
/// Asian sections cover the other cuisine options in the profile.
///
/// Figures are per the stated portion, drawn from USDA FoodData Central and,
/// for the non-US sections, IFCT 2017 (Indian Food Composition Tables), rounded
/// to the precision that survives someone eyeballing a serving size. Sodium is
/// the weakest column — restaurant salt varies enormously — so it is used for
/// direction, not arithmetic.

/// `macros` is `[kcal, protein, carbs, fat, fibre, addedSugar, sodium]` for the
/// stated portion.
FoodDefinition _food(
  String id,
  String name,
  String portionLabel,
  List<num> macros, {
  Cuisine? cuisine,
  List<FoodTag> tags = const [],
  List<Allergy> allergens = const [],
  bool vegetarian = false,
  bool vegan = false,
  bool jainSafe = false,
  bool containsPork = false,
  bool containsAlcohol = false,
}) {
  return FoodDefinition(
    id: id,
    name: name,
    portionLabel: portionLabel,
    macros: Macros(
      calories: macros[0].round(),
      proteinG: macros[1].toDouble(),
      carbsG: macros[2].toDouble(),
      fatG: macros[3].toDouble(),
      fibreG: macros[4].toDouble(),
      addedSugarG: macros[5].toDouble(),
      sodiumMg: macros[6].round(),
    ),
    cuisine: cuisine,
    tags: tags,
    allergens: allergens,
    // Vegan implies vegetarian; declaring both at every call site invites drift.
    vegetarian: vegan ? true : vegetarian,
    vegan: vegan,
    jainSafe: jainSafe,
    containsPork: containsPork,
    containsAlcohol: containsAlcohol,
  );
}

final List<FoodDefinition> foodDatabase = [
  // ---------------------------------------------------------------------------
  // American — breakfast
  // ---------------------------------------------------------------------------
  _food(
    'scrambled-eggs',
    'Scrambled eggs',
    '2 eggs with butter',
    [220, 13, 2, 18, 0, 0, 320],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.eggs, Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'turkey-bacon',
    'Turkey bacon',
    '3 slices',
    [120, 9, 1, 9, 0, 0, 560],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.ultraProcessed],
  ),
  _food(
    'breakfast-sausage',
    'Breakfast sausage links',
    '3 links',
    [260, 12, 2, 23, 0, 0, 560],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.ultraProcessed],
    containsPork: true,
  ),
  _food(
    'hash-browns',
    'Hash browns',
    '1 cup',
    [180, 2, 22, 9, 2, 0, 320],
    cuisine: Cuisine.american,
    tags: [FoodTag.fried],
    vegan: true,
  ),
  _food(
    'pancakes-syrup',
    'Pancakes with syrup',
    '3 pancakes',
    [430, 8, 78, 9, 1.4, 24, 590],
    cuisine: Cuisine.american,
    tags: [FoodTag.sugary],
    allergens: [Allergy.gluten, Allergy.dairy, Allergy.eggs],
    vegetarian: true,
  ),
  _food(
    'waffle',
    'Belgian waffle with syrup',
    '1 waffle',
    [350, 8, 45, 15, 1.2, 14, 450],
    cuisine: Cuisine.american,
    tags: [FoodTag.sugary],
    allergens: [Allergy.gluten, Allergy.dairy, Allergy.eggs],
    vegetarian: true,
  ),
  _food(
    'biscuits-gravy',
    'Biscuits and sausage gravy',
    '1 serving',
    [520, 14, 42, 32, 1.8, 4, 980],
    cuisine: Cuisine.american,
    tags: [FoodTag.ultraProcessed],
    allergens: [Allergy.gluten, Allergy.dairy],
    containsPork: true,
  ),
  _food(
    'bagel-cream-cheese',
    'Bagel with cream cheese',
    '1 bagel',
    [380, 12, 56, 11, 2, 6, 560],
    cuisine: Cuisine.american,
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'breakfast-burrito',
    'Breakfast burrito',
    '1 wrap, ~280 g',
    [450, 22, 38, 24, 3, 2, 780],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten, Allergy.dairy, Allergy.eggs],
  ),

  // ---------------------------------------------------------------------------
  // American — lunch & dinner
  // ---------------------------------------------------------------------------
  _food(
    'grilled-chicken-sandwich',
    'Grilled chicken sandwich',
    '1 sandwich',
    [420, 34, 38, 14, 3, 4, 890],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten],
  ),
  _food(
    'turkey-sandwich',
    'Turkey sandwich, whole wheat',
    '1 sandwich',
    [360, 26, 38, 10, 5, 4, 980],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.wholegrain],
    allergens: [Allergy.gluten],
  ),
  _food(
    'grilled-cheese',
    'Grilled cheese sandwich',
    '1 sandwich',
    [400, 16, 34, 22, 1.4, 3, 760],
    cuisine: Cuisine.american,
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'pb-and-j',
    'Peanut butter and jelly sandwich',
    '1 sandwich',
    [350, 12, 45, 14, 3.2, 18, 380],
    cuisine: Cuisine.american,
    allergens: [Allergy.peanuts, Allergy.gluten],
    vegetarian: true,
  ),
  _food(
    'tuna-salad-sandwich',
    'Tuna salad sandwich',
    '1 sandwich',
    [380, 26, 32, 15, 2.4, 4, 720],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.fish, Allergy.gluten, Allergy.eggs],
  ),
  _food(
    'caesar-salad-chicken',
    'Caesar salad with chicken',
    '1 large bowl, ~350 g',
    [420, 32, 14, 26, 3, 2, 820],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.gluten, Allergy.dairy, Allergy.fish],
  ),
  _food(
    'cobb-salad',
    'Cobb salad',
    '1 large bowl, ~380 g',
    [450, 28, 12, 32, 4.4, 2, 780],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.eggs, Allergy.dairy],
  ),
  _food(
    'chicken-noodle-soup',
    'Chicken noodle soup',
    '1 bowl, ~300 mL',
    [220, 16, 26, 5, 1.6, 0, 980],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten],
  ),
  _food(
    'clam-chowder',
    'New England clam chowder',
    '1 bowl, ~280 mL',
    [280, 12, 22, 16, 1.2, 0, 980],
    cuisine: Cuisine.american,
    allergens: [Allergy.shellfish, Allergy.dairy, Allergy.gluten],
  ),
  _food(
    'turkey-chili',
    'Turkey chili',
    '1 bowl, ~300 g',
    [320, 28, 28, 10, 8, 2, 780],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.ironRich],
  ),
  _food(
    'meatloaf',
    'Meatloaf',
    '1 slice, ~150 g',
    [320, 24, 14, 18, 0.8, 3, 620],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten, Allergy.eggs],
  ),
  _food(
    'pot-roast',
    'Pot roast with vegetables',
    '1 plate, ~350 g',
    [380, 32, 18, 18, 3, 0, 520],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.ironRich],
  ),
  _food(
    'steak-baked-potato',
    'Grilled steak with baked potato',
    '1 plate, ~350 g',
    [520, 42, 34, 22, 4, 0, 480],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.ironRich],
  ),
  _food(
    'bbq-pulled-pork',
    'BBQ pulled pork sandwich',
    '1 sandwich',
    [520, 28, 52, 20, 2, 12, 980],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten],
    containsPork: true,
  ),
  _food(
    'buffalo-wings',
    'Buffalo wings',
    '6 pieces',
    [430, 28, 4, 32, 0.4, 0, 1240],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.fried],
    allergens: [Allergy.dairy],
  ),
  _food(
    'mac-and-cheese',
    'Mac and cheese',
    '1 cup',
    [370, 14, 42, 15, 1.4, 3, 780],
    cuisine: Cuisine.american,
    tags: [FoodTag.ultraProcessed],
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'corn-on-the-cob',
    'Corn on the cob',
    '1 ear with butter',
    [120, 3.5, 27, 1.5, 3, 0, 20],
    cuisine: Cuisine.american,
    tags: [FoodTag.highFibre],
    vegetarian: true,
  ),
  _food(
    'coleslaw',
    'Coleslaw',
    '1 cup',
    [150, 1.5, 15, 10, 1.8, 8, 260],
    cuisine: Cuisine.american,
    allergens: [Allergy.eggs],
    vegetarian: true,
  ),
  _food(
    'cornbread',
    'Cornbread',
    '1 slice',
    [180, 3.5, 28, 6, 1.2, 6, 320],
    cuisine: Cuisine.american,
    allergens: [Allergy.gluten, Allergy.dairy, Allergy.eggs],
    vegetarian: true,
  ),

  // ---------------------------------------------------------------------------
  // American — snacks, desserts & drinks
  // ---------------------------------------------------------------------------
  _food(
    'apple-pie',
    'Apple pie',
    '1 slice',
    [296, 2.4, 42, 13, 2, 19, 320],
    cuisine: Cuisine.american,
    tags: [FoodTag.sugary, FoodTag.ultraProcessed],
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'soft-pretzel',
    'Soft pretzel',
    '1 large',
    [340, 9, 72, 2, 2.4, 4, 840],
    cuisine: Cuisine.american,
    allergens: [Allergy.gluten],
    vegan: true,
  ),
  _food(
    'popcorn',
    'Popcorn, air-popped',
    '3 cups',
    [93, 3, 19, 1, 3.5, 0, 2],
    cuisine: Cuisine.american,
    tags: [FoodTag.wholegrain, FoodTag.highFibre],
    vegan: true,
  ),
  _food(
    'granola-bar',
    'Granola bar',
    '1 bar',
    [140, 3, 22, 5, 1.6, 10, 90],
    cuisine: Cuisine.american,
    tags: [FoodTag.sugary],
    allergens: [Allergy.gluten, Allergy.treeNuts],
    vegetarian: true,
  ),
  _food(
    'trail-mix',
    'Trail mix',
    '1/4 cup, ~35 g',
    [170, 5, 15, 11, 2.4, 6, 40],
    cuisine: Cuisine.american,
    allergens: [Allergy.treeNuts, Allergy.peanuts],
    vegan: true,
  ),
  _food(
    'protein-bar',
    'Protein bar',
    '1 bar',
    [200, 20, 22, 7, 3, 5, 220],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.dairy, Allergy.soy],
    vegetarian: true,
  ),
  _food(
    'peanut-butter',
    'Peanut butter',
    '2 tbsp',
    [190, 7, 7, 16, 2, 3, 150],
    cuisine: Cuisine.american,
    allergens: [Allergy.peanuts],
    vegan: true,
  ),
  _food(
    'string-cheese',
    'Mozzarella string cheese',
    '1 stick',
    [80, 7, 1, 6, 0, 0, 200],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.calciumRich, FoodTag.lowCarb],
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'sweet-potato-fries',
    'Sweet potato fries',
    'medium serving, ~120 g',
    [330, 3.5, 48, 14, 4.4, 4, 480],
    cuisine: Cuisine.american,
    tags: [FoodTag.fried],
    vegan: true,
  ),
  _food(
    'sweet-tea',
    'Sweet tea',
    '16 fl oz',
    [140, 0, 36, 0, 0, 34, 20],
    cuisine: Cuisine.american,
    tags: [FoodTag.sugary],
    vegan: true,
  ),
  _food(
    'lemonade',
    'Lemonade',
    '12 fl oz',
    [150, 0, 39, 0, 0, 36, 10],
    cuisine: Cuisine.american,
    tags: [FoodTag.sugary],
    vegan: true,
  ),
  _food(
    'chocolate-milkshake',
    'Chocolate milkshake',
    '12 fl oz',
    [530, 10, 80, 18, 1.2, 74, 250],
    cuisine: Cuisine.american,
    tags: [FoodTag.sugary, FoodTag.ultraProcessed],
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),

  // ---------------------------------------------------------------------------
  // Mexican & Tex-Mex
  // ---------------------------------------------------------------------------
  _food(
    'chicken-burrito-bowl',
    'Chicken burrito bowl',
    '1 bowl, ~450 g',
    [560, 38, 58, 18, 9, 2, 1180],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highProtein, FoodTag.highFibre],
  ),
  _food(
    'chicken-tacos',
    'Grilled chicken tacos',
    '3 tacos',
    [420, 30, 36, 16, 4, 2, 780],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten, Allergy.dairy],
  ),
  _food(
    'shrimp-tacos',
    'Shrimp tacos',
    '3 tacos',
    [390, 26, 34, 14, 3.6, 2, 720],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.shellfish, Allergy.gluten],
  ),
  _food(
    'steak-quesadilla',
    'Steak quesadilla',
    '1 quesadilla',
    [560, 32, 38, 30, 2.4, 2, 980],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten, Allergy.dairy],
  ),
  _food(
    'chicken-fajitas',
    'Chicken fajitas with tortillas',
    '1 plate, ~400 g',
    [520, 36, 48, 18, 5.4, 2, 980],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.gluten],
  ),
  _food(
    'carne-asada-plate',
    'Carne asada plate with rice and beans',
    '1 plate, ~450 g',
    [680, 42, 62, 26, 9, 0, 1120],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highProtein, FoodTag.ironRich],
  ),
  _food(
    'black-beans',
    'Black beans',
    '1 cup',
    [227, 15, 40, 1, 15, 0, 2],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.ironRich],
    vegan: true,
  ),
  _food(
    'guacamole-chips',
    'Guacamole with tortilla chips',
    'small bowl + chips',
    [380, 5, 36, 24, 8, 0, 420],
    cuisine: Cuisine.mexican,
    tags: [FoodTag.highFibre, FoodTag.fried],
    allergens: [Allergy.gluten],
    vegan: true,
  ),

  // ---------------------------------------------------------------------------
  // North Indian
  // ---------------------------------------------------------------------------
  _food(
    'roti',
    'Roti / chapati',
    '1 medium, ~40 g',
    [104, 3.1, 20, 1.4, 2.6, 0, 95],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.wholegrain, FoodTag.highFibre],
    allergens: [Allergy.gluten],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'naan',
    'Butter naan',
    '1 piece, ~90 g',
    [262, 7.4, 42, 7.2, 1.8, 2, 420],
    cuisine: Cuisine.northIndian,
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'aloo-paratha',
    'Aloo paratha',
    '1 piece with ghee',
    [318, 6.8, 44, 13, 3.4, 0, 380],
    cuisine: Cuisine.northIndian,
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'plain-rice',
    'Steamed white rice',
    '1 cup cooked, ~150 g',
    [205, 4.3, 45, 0.4, 0.6, 0, 2],
    cuisine: Cuisine.northIndian,
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'jeera-rice',
    'Jeera rice',
    '1 cup, ~160 g',
    [265, 4.6, 46, 7, 1, 0, 320],
    cuisine: Cuisine.northIndian,
    vegetarian: true,
  ),
  _food(
    'brown-rice',
    'Brown rice',
    '1 cup cooked, ~150 g',
    [216, 5, 45, 1.8, 3.5, 0, 5],
    tags: [FoodTag.wholegrain, FoodTag.highFibre],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'dal-tadka',
    'Dal tadka',
    '1 bowl, ~200 g',
    [198, 11.5, 26, 5.4, 7.8, 0, 460],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.ironRich],
    vegetarian: true,
  ),
  _food(
    'dal-makhani',
    'Dal makhani',
    '1 bowl, ~200 g',
    [327, 12, 28, 18, 8.2, 0, 620],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein, FoodTag.highFibre],
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'rajma',
    'Rajma masala',
    '1 bowl, ~200 g',
    [245, 12.8, 34, 6.5, 11, 0, 540],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.ironRich],
    vegetarian: true,
  ),
  _food(
    'chole',
    'Chole (chickpea curry)',
    '1 bowl, ~200 g',
    [269, 12.2, 36, 8.4, 10.6, 0, 580],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.ironRich],
    vegetarian: true,
  ),
  _food(
    'palak-paneer',
    'Palak paneer',
    '1 bowl, ~200 g',
    [305, 14.5, 12, 23, 4.6, 0, 610],
    cuisine: Cuisine.northIndian,
    tags: [
      FoodTag.highProtein,
      FoodTag.ironRich,
      FoodTag.leafyGreen,
      FoodTag.calciumRich,
    ],
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'paneer-tikka',
    'Paneer tikka (dry)',
    '6 pieces, ~150 g',
    [286, 18.5, 9, 20, 2, 0, 520],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein, FoodTag.lowCarb, FoodTag.calciumRich],
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'bhindi-masala',
    'Bhindi masala',
    '1 bowl, ~150 g',
    [148, 3.2, 12, 10, 5.4, 0, 410],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highFibre, FoodTag.lowCarb],
    vegan: true,
  ),
  _food(
    'mixed-sabzi',
    'Mixed vegetable sabzi',
    '1 bowl, ~180 g',
    [135, 4.1, 16, 6.4, 6.2, 0, 390],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highFibre],
    vegan: true,
  ),
  _food(
    'tandoori-chicken',
    'Tandoori chicken',
    '2 pieces, ~200 g',
    [312, 41, 4, 14, 0.8, 0, 690],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.dairy],
  ),
  _food(
    'chicken-tikka',
    'Chicken tikka (dry)',
    '6 pieces, ~150 g',
    [268, 34, 5, 12, 0.6, 0, 640],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.dairy],
  ),
  _food(
    'butter-chicken',
    'Butter chicken',
    '1 bowl, ~220 g',
    [438, 27, 14, 31, 1.8, 4, 780],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.dairy, Allergy.treeNuts],
  ),
  _food(
    'chicken-biryani',
    'Chicken biryani',
    '1 plate, ~350 g',
    [582, 28, 68, 21, 3.6, 0, 980],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.dairy],
  ),
  _food(
    'raita',
    'Cucumber raita',
    '1 small bowl, ~120 g',
    [72, 4.2, 6, 3.4, 0.8, 0, 210],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.probiotic, FoodTag.calciumRich],
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'samosa',
    'Samosa',
    '1 piece, ~60 g',
    [198, 3.6, 24, 10, 2.2, 0, 340],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.fried, FoodTag.ultraProcessed],
    allergens: [Allergy.gluten],
    vegetarian: true,
  ),
  _food(
    'pakora',
    'Onion pakora',
    '5 pieces, ~80 g',
    [284, 6.4, 28, 16, 3.4, 0, 460],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.fried],
    vegan: true,
  ),
  _food(
    'gulab-jamun',
    'Gulab jamun',
    '2 pieces',
    [312, 4.2, 46, 12, 0.4, 34, 120],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.sugary, FoodTag.ultraProcessed],
    allergens: [Allergy.dairy, Allergy.gluten],
    vegetarian: true,
  ),
  _food(
    'sweet-lassi',
    'Sweet lassi',
    '1 glass, 250 mL',
    [216, 6.8, 34, 5.6, 0, 22, 95],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.sugary, FoodTag.probiotic, FoodTag.calciumRich],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'masala-chai',
    'Masala chai with sugar',
    '1 cup, 150 mL',
    [98, 2.4, 14, 3.4, 0, 10, 45],
    cuisine: Cuisine.northIndian,
    tags: [FoodTag.sugary],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),

  // ---------------------------------------------------------------------------
  // South Indian
  // ---------------------------------------------------------------------------
  _food(
    'idli',
    'Idli',
    '2 pieces',
    [116, 4.2, 24, 0.6, 1.4, 0, 220],
    cuisine: Cuisine.southIndian,
    tags: [FoodTag.probiotic],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'plain-dosa',
    'Plain dosa',
    '1 large',
    [168, 4.4, 28, 4.6, 1.6, 0, 240],
    cuisine: Cuisine.southIndian,
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'masala-dosa',
    'Masala dosa',
    '1 large with filling',
    [312, 6.8, 46, 11, 3.8, 0, 480],
    cuisine: Cuisine.southIndian,
    vegetarian: true,
  ),
  _food(
    'uttapam',
    'Onion uttapam',
    '1 piece',
    [204, 6.2, 32, 5.6, 2.8, 0, 320],
    cuisine: Cuisine.southIndian,
    vegan: true,
  ),
  _food(
    'sambar',
    'Sambar',
    '1 bowl, ~180 g',
    [142, 7.8, 20, 3.6, 6.4, 0, 520],
    cuisine: Cuisine.southIndian,
    tags: [FoodTag.highFibre, FoodTag.ironRich],
    vegan: true,
  ),
  _food(
    'rasam',
    'Rasam',
    '1 bowl, ~180 g',
    [68, 3.2, 10, 1.8, 2.4, 0, 480],
    cuisine: Cuisine.southIndian,
    tags: [FoodTag.lowCarb],
    vegan: true,
  ),
  _food(
    'coconut-chutney',
    'Coconut chutney',
    '2 tbsp',
    [86, 1.4, 4, 7.4, 2.2, 0, 140],
    cuisine: Cuisine.southIndian,
    vegan: true,
  ),
  _food(
    'upma',
    'Upma',
    '1 bowl, ~180 g',
    [232, 5.4, 34, 8.2, 2.6, 0, 420],
    cuisine: Cuisine.southIndian,
    vegetarian: true,
  ),
  _food(
    'ven-pongal',
    'Ven pongal',
    '1 bowl, ~200 g',
    [286, 8.2, 42, 9.4, 3.2, 0, 460],
    cuisine: Cuisine.southIndian,
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'curd-rice',
    'Curd rice',
    '1 bowl, ~220 g',
    [242, 7.6, 38, 6.2, 1, 0, 380],
    cuisine: Cuisine.southIndian,
    tags: [FoodTag.probiotic, FoodTag.calciumRich],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'fish-curry',
    'Kerala fish curry',
    '1 bowl, ~200 g',
    [232, 24, 8, 12, 1.6, 0, 620],
    cuisine: Cuisine.southIndian,
    tags: [FoodTag.highProtein, FoodTag.omega3Rich, FoodTag.lowCarb],
    allergens: [Allergy.fish],
  ),
  _food(
    'medu-vada',
    'Medu vada',
    '2 pieces',
    [268, 7.2, 26, 15, 4.2, 0, 380],
    cuisine: Cuisine.southIndian,
    tags: [FoodTag.fried],
    vegan: true,
  ),
  _food(
    'filter-coffee',
    'Filter coffee with sugar',
    '1 cup, 120 mL',
    [86, 2.8, 11, 3.2, 0, 8, 40],
    cuisine: Cuisine.southIndian,
    tags: [FoodTag.sugary],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),

  // ---------------------------------------------------------------------------
  // Mediterranean & Middle Eastern
  // ---------------------------------------------------------------------------
  _food(
    'grilled-chicken-salad',
    'Grilled chicken salad',
    '1 large bowl, ~320 g',
    [364, 38, 14, 18, 5.2, 0, 520],
    cuisine: Cuisine.mediterranean,
    tags: [
      FoodTag.highProtein,
      FoodTag.lowCarb,
      FoodTag.highFibre,
      FoodTag.leafyGreen,
    ],
  ),
  _food(
    'greek-salad',
    'Greek salad',
    '1 bowl, ~250 g',
    [248, 8.4, 12, 19, 4.4, 0, 640],
    cuisine: Cuisine.mediterranean,
    tags: [FoodTag.highFibre, FoodTag.lowCarb, FoodTag.calciumRich],
    allergens: [Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'grilled-salmon',
    'Grilled salmon fillet',
    '1 fillet, ~170 g',
    [354, 39, 0, 21, 0, 0, 180],
    cuisine: Cuisine.mediterranean,
    tags: [FoodTag.highProtein, FoodTag.omega3Rich, FoodTag.lowCarb],
    allergens: [Allergy.fish],
  ),
  _food(
    'hummus-pita',
    'Hummus with wholewheat pita',
    '3 tbsp + 1 pita',
    [312, 10.4, 42, 12, 7.4, 0, 480],
    cuisine: Cuisine.middleEastern,
    tags: [FoodTag.highFibre, FoodTag.wholegrain],
    allergens: [Allergy.sesame, Allergy.gluten],
    vegan: true,
  ),
  _food(
    'falafel-wrap',
    'Falafel wrap',
    '1 wrap, ~280 g',
    [486, 15, 58, 21, 9.2, 2, 780],
    cuisine: Cuisine.middleEastern,
    tags: [FoodTag.highFibre, FoodTag.fried],
    allergens: [Allergy.gluten, Allergy.sesame],
    vegan: true,
  ),
  _food(
    'tabbouleh',
    'Quinoa tabbouleh',
    '1 bowl, ~200 g',
    [232, 7.2, 32, 8.6, 6.8, 0, 320],
    cuisine: Cuisine.middleEastern,
    tags: [FoodTag.highFibre, FoodTag.wholegrain],
    vegan: true,
  ),
  _food(
    'lentil-soup',
    'Lentil soup',
    '1 bowl, ~300 mL',
    [186, 11.4, 28, 3.2, 8.6, 0, 620],
    cuisine: Cuisine.middleEastern,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.ironRich],
    vegan: true,
  ),
  _food(
    'shakshuka',
    'Shakshuka',
    '1 pan, ~300 g',
    [284, 16.2, 16, 18, 4.8, 0, 680],
    cuisine: Cuisine.middleEastern,
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.eggs],
    vegetarian: true,
  ),
  _food(
    'chicken-shawarma-plate',
    'Chicken shawarma plate',
    '1 plate, ~350 g',
    [524, 42, 38, 24, 5.4, 0, 940],
    cuisine: Cuisine.middleEastern,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.sesame, Allergy.dairy],
  ),

  // ---------------------------------------------------------------------------
  // East Asian
  // ---------------------------------------------------------------------------
  _food(
    'salmon-sushi',
    'Salmon nigiri',
    '6 pieces',
    [312, 22, 42, 6.4, 1.2, 4, 620],
    cuisine: Cuisine.japanese,
    tags: [FoodTag.highProtein, FoodTag.omega3Rich],
    allergens: [Allergy.fish, Allergy.soy],
  ),
  _food(
    'miso-soup',
    'Miso soup',
    '1 bowl, ~200 mL',
    [58, 4.2, 6, 2.2, 1.4, 0, 720],
    cuisine: Cuisine.japanese,
    tags: [FoodTag.probiotic, FoodTag.lowCarb],
    allergens: [Allergy.soy],
    vegan: true,
  ),
  _food(
    'chicken-teriyaki',
    'Chicken teriyaki with rice',
    '1 plate, ~380 g',
    [612, 38, 76, 16, 2.4, 14, 1180],
    cuisine: Cuisine.japanese,
    tags: [FoodTag.highProtein],
    allergens: [Allergy.soy, Allergy.gluten],
  ),
  _food(
    'pho',
    'Beef pho',
    '1 bowl, ~500 mL',
    [418, 28, 52, 9.4, 3.2, 2, 1240],
    cuisine: Cuisine.eastAsian,
    tags: [FoodTag.highProtein, FoodTag.ironRich],
    allergens: [Allergy.fish, Allergy.soy],
  ),
  _food(
    'pad-thai',
    'Pad Thai with chicken',
    '1 plate, ~350 g',
    [648, 26, 82, 24, 4.2, 16, 1320],
    cuisine: Cuisine.thai,
    allergens: [Allergy.peanuts, Allergy.eggs, Allergy.fish, Allergy.soy],
  ),
  _food(
    'tofu-stirfry',
    'Tofu and vegetable stir-fry',
    '1 plate, ~300 g',
    [318, 21, 22, 17, 6.4, 4, 760],
    cuisine: Cuisine.eastAsian,
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.calciumRich],
    allergens: [Allergy.soy, Allergy.sesame],
    vegan: true,
  ),
  _food(
    'edamame',
    'Edamame',
    '1 cup, ~155 g',
    [188, 18.4, 14, 8.1, 8, 0, 380],
    cuisine: Cuisine.japanese,
    tags: [FoodTag.highProtein, FoodTag.highFibre],
    allergens: [Allergy.soy],
    vegan: true,
  ),

  // ---------------------------------------------------------------------------
  // Everyday staples
  // ---------------------------------------------------------------------------
  _food(
    'oats-porridge',
    'Oats porridge with milk',
    '1 bowl, ~250 g',
    [242, 10.2, 38, 5.8, 5.4, 0, 120],
    tags: [FoodTag.wholegrain, FoodTag.highFibre],
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'greek-yoghurt',
    'Greek yoghurt, plain',
    '1 cup, ~200 g',
    [146, 20, 8, 4, 0, 0, 72],
    tags: [
      FoodTag.highProtein,
      FoodTag.probiotic,
      FoodTag.calciumRich,
      FoodTag.lowCarb,
    ],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'boiled-eggs',
    'Boiled eggs',
    '2 large',
    [156, 12.6, 1.1, 11, 0, 0, 124],
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.eggs],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'veg-omelette',
    'Vegetable omelette',
    '2 eggs',
    [226, 14.2, 4.2, 17, 1.2, 0, 380],
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.eggs],
    vegetarian: true,
  ),
  _food(
    'chicken-breast',
    'Grilled chicken breast',
    '150 g',
    [248, 46, 0, 5.4, 0, 0, 132],
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
  ),
  _food(
    'paneer',
    'Paneer, pan-seared',
    '100 g',
    [296, 18.3, 3.6, 23, 0, 0, 22],
    tags: [FoodTag.highProtein, FoodTag.lowCarb, FoodTag.calciumRich],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'tofu',
    'Firm tofu',
    '150 g',
    [216, 23, 5.4, 13, 2.4, 0, 24],
    tags: [FoodTag.highProtein, FoodTag.lowCarb, FoodTag.calciumRich],
    allergens: [Allergy.soy],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'whey-shake',
    'Whey protein shake',
    '1 scoop in water',
    [124, 25, 3, 1.5, 0, 1, 90],
    tags: [FoodTag.highProtein, FoodTag.lowCarb],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'cooked-spinach',
    'Cooked spinach',
    '1 cup, ~180 g',
    [82, 5.3, 6.8, 3.2, 4.3, 0, 180],
    tags: [
      FoodTag.ironRich,
      FoodTag.leafyGreen,
      FoodTag.highFibre,
      FoodTag.lowCarb,
    ],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'chickpea-salad',
    'Chickpea salad',
    '1 bowl, ~250 g',
    [312, 13.4, 38, 12, 11.2, 0, 420],
    tags: [FoodTag.highProtein, FoodTag.highFibre, FoodTag.ironRich],
    vegan: true,
  ),
  _food(
    'quinoa',
    'Cooked quinoa',
    '1 cup, ~185 g',
    [222, 8.1, 39, 3.6, 5.2, 0, 13],
    tags: [FoodTag.wholegrain, FoodTag.highFibre, FoodTag.highProtein],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'sweet-potato',
    'Baked sweet potato',
    '1 medium, ~150 g',
    [162, 3.6, 37, 0.2, 5.4, 0, 72],
    tags: [FoodTag.highFibre],
    vegan: true,
  ),
  _food(
    'avocado-toast',
    'Avocado on wholegrain toast',
    '2 slices',
    [346, 9.2, 34, 20, 9.4, 0, 420],
    tags: [FoodTag.highFibre, FoodTag.wholegrain],
    allergens: [Allergy.gluten],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'banana',
    'Banana',
    '1 medium, ~120 g',
    [105, 1.3, 27, 0.4, 3.1, 0, 1],
    tags: [FoodTag.highFibre],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'orange',
    'Orange',
    '1 medium',
    [62, 1.2, 15, 0.2, 3.1, 0, 0],
    tags: [FoodTag.vitaminCRich, FoodTag.highFibre],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'guava',
    'Guava',
    '1 medium, ~120 g',
    [68, 2.6, 14, 0.9, 5.4, 0, 2],
    tags: [FoodTag.vitaminCRich, FoodTag.highFibre],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'almonds',
    'Almonds',
    '20 pieces, ~24 g',
    [138, 5.1, 5.2, 12, 3, 0, 0],
    tags: [FoodTag.highFibre],
    allergens: [Allergy.treeNuts],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'walnuts',
    'Walnuts',
    '6 halves, ~20 g',
    [131, 3, 2.8, 13, 1.4, 0, 0],
    tags: [FoodTag.omega3Rich],
    allergens: [Allergy.treeNuts],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'black-coffee',
    'Black coffee',
    '1 cup',
    [4, 0.3, 0, 0, 0, 0, 5],
    tags: [FoodTag.lowCarb],
    vegan: true,
    jainSafe: true,
  ),

  // ---------------------------------------------------------------------------
  // The ones that make weekly patterns interesting
  // ---------------------------------------------------------------------------
  _food(
    'cola',
    'Cola',
    '330 mL can',
    [139, 0, 35, 0, 0, 35, 15],
    tags: [FoodTag.sugary, FoodTag.ultraProcessed],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'orange-juice',
    'Orange juice, packaged',
    '250 mL',
    [112, 1.7, 26, 0.5, 0.5, 22, 8],
    tags: [FoodTag.sugary],
    vegan: true,
    jainSafe: true,
  ),
  _food(
    'chocolate-bar',
    'Milk chocolate bar',
    '45 g',
    [238, 3.4, 26, 13, 1.4, 24, 42],
    tags: [FoodTag.sugary, FoodTag.ultraProcessed],
    allergens: [Allergy.dairy, Allergy.soy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'ice-cream',
    'Vanilla ice cream',
    '2 scoops, ~130 g',
    [274, 4.6, 32, 14, 0.8, 28, 106],
    tags: [FoodTag.sugary, FoodTag.ultraProcessed],
    allergens: [Allergy.dairy],
    vegetarian: true,
    jainSafe: true,
  ),
  _food(
    'fries',
    'French fries',
    'medium serving, ~120 g',
    [378, 4.2, 48, 18, 4.4, 0, 340],
    tags: [FoodTag.fried, FoodTag.ultraProcessed],
    vegan: true,
  ),
  _food(
    'cheeseburger',
    'Cheeseburger',
    '1 regular',
    [536, 27, 42, 29, 2.2, 8, 1120],
    cuisine: Cuisine.american,
    tags: [FoodTag.ultraProcessed],
    allergens: [Allergy.gluten, Allergy.dairy, Allergy.sesame],
  ),
  _food(
    'pizza-slice',
    'Pizza, cheese',
    '2 slices',
    [568, 24, 66, 22, 3.6, 6, 1240],
    cuisine: Cuisine.continental,
    tags: [FoodTag.ultraProcessed],
    allergens: [Allergy.gluten, Allergy.dairy],
    vegetarian: true,
  ),
  _food(
    'beer',
    'Beer',
    '330 mL',
    [143, 1.2, 11, 0, 0, 0, 14],
    vegan: true,
    jainSafe: true,
    containsAlcohol: true,
  ),
  _food(
    'bacon',
    'Bacon',
    '3 rashers',
    [161, 12, 0.6, 12, 0, 0, 581],
    cuisine: Cuisine.american,
    tags: [FoodTag.highProtein, FoodTag.ultraProcessed],
    containsPork: true,
  ),
];

final Map<String, FoodDefinition> _byId = {
  for (final item in foodDatabase) item.id: item,
};

FoodDefinition? findFood(String id) => _byId[id];

/// Substring search over names, ranked so a prefix match beats a mid-word one.
///
/// Deliberately not fuzzy — a typo-tolerant matcher that silently logs "dal
/// makhani" when the user typed "dal makhni" is fine, but one that logs
/// "cheeseburger" for "chana" is not.
List<FoodDefinition> searchFoods(String query, {int limit = 20}) {
  final needle = query.trim().toLowerCase();
  if (needle.isEmpty) return const [];

  final scored = <({FoodDefinition item, int score})>[];
  for (final item in foodDatabase) {
    final index = item.name.toLowerCase().indexOf(needle);
    if (index == -1) continue;
    scored.add((item: item, score: index == 0 ? 0 : 1 + index));
  }

  scored.sort((a, b) {
    final byScore = a.score.compareTo(b.score);
    return byScore != 0 ? byScore : a.item.name.compareTo(b.item.name);
  });

  return scored.take(limit).map((e) => e.item).toList();
}

List<FoodDefinition> foodsByTag(FoodTag tag) =>
    foodDatabase.where((item) => item.tags.contains(tag)).toList();

/// Dishes plausible at a restaurant of this cuisine.
///
/// An unknown cuisine gets the pan-cuisine staples rather than nothing — a
/// "restaurant" with no type tags still serves grilled chicken and salad.
List<FoodDefinition> menuForCuisine(Cuisine? cuisine) =>
    foodDatabase.where((food) => food.cuisine == cuisine).toList();
