// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzjxHeKMkQzWhkfMCT0f67JKd6ID3_fFc',
    appId: '1:368943821492:web:be48a024e62d9649d15de1',
    messagingSenderId: '368943821492',
    projectId: 'agentrix-health-70a12',
    authDomain: 'agentrix-health-70a12.firebaseapp.com',
    storageBucket: 'agentrix-health-70a12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4OrGJfRcOIfTy1g7yncRXT-HH9NiSHrQ',
    appId: '1:368943821492:android:6a58e0c7d41a099cd15de1',
    messagingSenderId: '368943821492',
    projectId: 'agentrix-health-70a12',
    storageBucket: 'agentrix-health-70a12.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHBjoKBKFydljYGU7yf13CX20-M5ZNHQ',
    appId: '1:368943821492:ios:3d545096e4564a42d15de1',
    messagingSenderId: '368943821492',
    projectId: 'agentrix-health-70a12',
    storageBucket: 'agentrix-health-70a12.firebasestorage.app',
    androidClientId: '368943821492-e2dn0fgi0oluucflmi70jcdan1dnpjmb.apps.googleusercontent.com',
    iosClientId: '368943821492-bi43h31p6akhhbhgslphn91f4mtc2q7t.apps.googleusercontent.com',
    iosBundleId: 'com.stratava.agentrixhealth',
  );
}
